### ISSUE TITLE
Ошибка повторной настройки

### ISSUE THREAD

**Issue by inviz-ize** [dentra/ha-pesc#1]
Добрй день!
Спасибо за интеграцию, очень классная реализация и прям то, что искал, но я столкнулся с проблемой. Через некоторое время использования после вызова службы вылезла ошибка, которая гласила, что авторизация не валидна. Решил зайти в саму интеграцию и перезапустить ее. После перезапуска получил сообщение о необходимости ее перенастройки, а в записях интергации данные аккаунта пропали. При попытке ввести данные аккаунта, получаю сообщение, что такой аккаунт уже существует. Подскажите, как такое можно вылечить без переустановки\ перенастройки интеграции?

![Снимок экрана 2023-06-20 в 13 19 54](https://github.com/dentra/ha-pesc/assets/9848808/ab4362ca-c25b-483d-ad4f-c981512c53cb)
![Снимок экрана 2023-06-20 в 13 20 15](https://github.com/dentra/ha-pesc/assets/9848808/4e419958-027e-4be8-87fb-b6d7eb27f42c)

**Comment by dentra** [comment]
Ошибку эту вроде исправлял, возможно не доконца.
Удалите интеграцию и добавьте заново, если поставите галочку "Сохранить пароль", то когда "протухнет" токен авторазиация будет делаться автоматически.

**Comment by inviz-ize** [comment]
Отлично, спасибо! Потестирую.
