### ISSUE TITLE
Стоимость тарифа 

### ISSUE THREAD

**Issue by Valen13776** [dentra/ha-pesc#12]
Добрый день!
Спасибо ОГРОМНОЕ за Вашу работу.

Столкнулся с такой проблемой: добавил интеграцию. Все данные подтягиваются кроме стоимости тарифа "Круглосуточный".
Включил логинг. В ответе сервера информация есть.
`{
        "header": "Электроэнергия",
        "blockType": "TABLE",
        "content": [
            {
                "name": "Тип тарифа",
                "code": null,
                "description": null,
                "value": "Однотарифный",
                "columns": null,
                "rank": null
            },
            {
                "name": "Круглосуточный",
                "code": null,
                "description": "",
                "value": null,
                "columns": [
                    {
                        "code": "1",
                        "value": "4.64"
                    }
                ],
                "rank": 1
            }
        ],
        "subHeader": "Подробная информация о тарифах размещена в разделе <a target=\"_blank\" href=\"https://ikus.pesc.ru/help/faq\">Помощь</a>",
        "rank": null,
        "columns": [
            {
                "code": "1",
                "name": "Тариф 1 диапазона потребления",
                "rank": 1
            }
        ]
    }`
Сенсор создаётся, но значение "Неизвестно".
Был бы признателен за решение.
Спасибо.

**Comment by dentra** [comment]
Доброго времени! А можно целиком всю строку?

**Comment by dentra** [comment]
Есть ли в логе предупреждение, начинающееся с «Unsupported tariff»?

**Comment by dentra** [comment]
Ох, они опять все поменяли, на электроэнергию все тарифы поехали, буду смотреть…
Пока отбой с дополнительным логом

**Comment by dentra** [comment]
а как у вас отображаются названия сенсоров?

**Comment by dentra** [comment]
можно проверять из мастера

**Comment by dentra** [comment]
пока не закрываю, т.к. самостоятельно не могу проверить работу тарифа "Однотарифный"

**Comment by Valen13776** [comment]
Заработало.
Спасибо!

![image](https://github.com/user-attachments/assets/c43da371-5236-494c-9160-a741061583a4)

**Comment by dentra** [comment]
огонь!

**Comment by Valen13776** [comment]
Нет желания/возможности разработать интеграцию для ТГК-1?

**Comment by dentra** [comment]
> Нет желания/возможности разработать интеграцию для ТГК-1?

на данный момент нет

**Comment by Valen13776** [comment]
Эх...
Жаль.
Спасибо за ту работу которую Вы делаете!
