### ISSUE TITLE
 тарифы недоступны

### ISSUE THREAD

**Issue by 532910** [dentra/ha-pesc#14]
![image](https://github.com/user-attachments/assets/48928c66-8491-4722-a2e2-6f678e8033a8)

reload не помогает

**Comment by 532910** [comment]
![image](https://github.com/user-attachments/assets/14f0e340-4e94-4fed-ac2b-19d146934506)

это история хелпера с таким шаблоном:
```Jinja
{%- if now().hour >= 7 and now().hour < 23 -%}
{{ states('sensor.pesc_electricity_rate_day') }}
{%- else -%}
{{ states('sensor.pesc_electricity_rate_night') }}
{%- endif -%}
```

до 2 июля 9 месяцев работало исправно, со 2 до 15 не работало, с 15 по 23 работало, и с 24 снова перестало

**Comment by dentra** [comment]
дубликат #12
поменяли структуру данных :(
занимаюсь

**Comment by dentra** [comment]
можно проверять из мастера

**Comment by 532910** [comment]
не знаете наиболее простой способ взять версию из мастера?

**Comment by dentra** [comment]
так в hacs -> pasc -> "Скачать повторно" и просто выбираете master...

**Comment by 532910** [comment]
Вот ещё такое соображение: если по какой-то причине не удаётся получить актуальные значения тарифов, то брать последние известные (и возможно ещё дату последнего успешного обновления указывать)
Наверное такое можно сделать через helper, хо было бы здорово через саму интеграцию

**Comment by dentra** [comment]
новый тикет на это заведите плиз, а то забуду 👼

**Comment by dentra** [comment]
тогда попробуйте так:
```yaml
service: update.install
target:
  entity_id: update.pesc_update
data:
  version: master
```
все можно сделать из gui: Панель Разработчика -> Службы -> Обновление: Установить обновление

**Comment by 532910** [comment]
вот так сделал: https://experimental.hacs.xyz/docs/use/entities/update/
подтверждаю, мастер работает

**Comment by dentra** [comment]
> вот так сделал

я именно этот способ и описал ;)

> мастер работает

отлично
