### ISSUE TITLE
Все сенсоры в kWh

### ISSUE THREAD

**Issue by inviz-ize** [dentra/ha-pesc#2]
Добрый день! В прошлых версиях интеграция получала и как-то сама правильно определяла единицы измерения на разные сущности. В последней версии все сенсоры имеют единицы измерения kWh, что в моем случае не очень корректно, так как помимо электроэнергии присутствуют еще и счетчики воды. Можно как-то это поправить? 
![IMG_1573](https://github.com/dentra/ha-pesc/assets/9848808/cac30ad9-00ba-4172-856e-a8f2ffd0800b)
![IMG_1574](https://github.com/dentra/ha-pesc/assets/9848808/f26936c0-1b45-460c-b86e-3427db91db0d)

**Comment by dentra** [comment]
Добрый день! Т.к. у меня, к сожалению, ЛК отображает только электроэнергию компонент и делался с расчетом на это. В любом случае я готов развивать функциональность. Сейчас внес изменения позволяющие разделить электроэнергию и все остальное. И вот для этого остального мне не хватает данных. Если сможете включить лог в режим отладки и прислать ответы сервера, доведу эти сенсоры до нормального состояния

лог включается так:
```yaml
logger:
  logs:
    custom_components.pesc: debug
```

**Comment by dentra** [comment]
нашел возможность определить тип потребления, реализовал, но нужна проверка т.к. в слепую делать это не очень удобно

**Comment by dentra** [comment]
на первом скрине в диагностике тариф на воду не отображается. в ЛК есть тариф?

**Comment by inviz-ize** [comment]
да, в ЛК есть. раньше причем, мне кажется, приходили и на воду в HA и на свет. 
![image](https://github.com/dentra/ha-pesc/assets/9848808/381506e7-280a-4e4d-99dd-725dcd1d41e9)

**Comment by dentra** [comment]
спасибо. а можно еще скрин с развернутыми атрибутами холодного водоснабжения?

**Comment by dentra** [comment]
проверяйте, все услуги и тарифы должны отображаться корректно

**Comment by 532910** [comment]
у меня вода в метрах кубических
