### ISSUE TITLE
Похоже, сайт поменял местами версию API  на v7. Не работает (пере)авторизация

### ISSUE THREAD

**Issue by devbis** [dentra/ha-pesc#20]
После замены v6 -> v7 тут https://github.com/dentra/ha-pesc/blob/master/custom_components/pesc/pesc_client.py#L229
и ещё в ряде мест компонент смог залогиниться и вроде заработал. 

На сайте v6/v7 вперемешку, но для авторизации и информации по аккаунту вроде перешли на v7.

**Comment by Valen13776** [comment]
В ряде каких мест?
Тоже не работает (((

**Comment by aleksman-piter** [comment]
Поддержу последнего комментатора, где именно поменять?
Тоже не работает повторная авторизация.

**Comment by aleksman-piter** [comment]
мне вроде помогло, номера строк немного не бьются.
pesc_client.py:229:            f"{self._API_URL}/v7/users/auth", headers=headers, json=payload
pesc_client.py:249:            f"{self._API_URL}/v7/accounts/{account_id}/meters/{meter_id}/reading",
pesc_client.py:289:            f"/v7/accounts/providers/{provider_id}/subservices"
pesc_client.py:324:        return await self._async_get(f"/v7/accounts/{account_id}/details")
на последних 2х строках по умолчанию было v7
@devbis Спасибо!

**Comment by dentra** [comment]
Да, опять поменяли, завтра поправлю

**Comment by devbis** [comment]
Исправлено в [releases/2024.7.2 ](https://github.com/dentra/ha-pesc/releases/tag/2024.7.2)
