### ISSUE TITLE
update values after `pesc.update_value` call

### ISSUE THREAD

**Issue by 532910** [dentra/ha-pesc#5]
вот я подал показания, они подались, всё ok: вижу в личном кабинете,
но `sensor.pesc_electricity_day` продолжает показывать старые значения
reload интеграции обновляет значения

хочется что бы интеграция обновляла значения после подачи

**Comment by dentra** [comment]
проблема все еще актуальна?

**Comment by 532910** [comment]
да

**Comment by 532910** [comment]
подозреваю, что истинная причина крылась в #13
