### ISSUE TITLE
add login by e-mail

### ISSUE THREAD

**Issue by 532910** [dentra/ha-pesc#6]
please add support to login by e-mail

**Comment by dentra** [comment]
К сожалению, это ограничение сервиса, логин возможен только по номеру телефона

**Comment by 532910** [comment]
сервис позволяет логиниться по почте:
![image](https://github.com/dentra/ha-pesc/assets/14617699/e4bee9a3-9777-4b21-90cf-f6f3f054be3a)


POST запрос:
https://ikus.pesc.ru/api/v7/users/auth
{"type":"EMAIL","login":"user@mail.com","password":"secret"}
